global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    basic_auth:
      username: 'admin'
      password: 'Prometheus@2024'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # add IP address of the host machine
  
  - job_name: 'mysql_exporter' 
    static_configs:
      - targets: ['amp_mysql_exporter:9104']